version: "3.3"

services:
  bot:
    container_name: parrot
    build:
        context: .
        target: dev
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
        TOKEN: ${TOKEN}
        GSHEET: ${GSHEET}
