version: "3.3"

services:
  bot:
    container_name: parrot
    build:
        context: .
    volumes:
      - .:/app/
      - /app/node_modules
      - /app/models
    environment:
        TOKEN: ${TOKEN}
        GSHEET: ${GSHEET}