version: "3.3"

services:
  bot:
    container_name: parrot
    build:
        context: .
        target: dev
    volumes:
      - .:/app/
      - /app/node_modules
      #- ./output/:/tmp/
    environment:
        TOKEN: ${TOKEN}
        GSHEET: ${GSHEET}
    #command: bash -c "python3 /app/src/python/fastspeech2/main.py"
    #command: bash -c "nodemon -L main.js"